name: Dart Analyze

on: [push]

jobs:
  analyze:
    name: Analyze Dart Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart Analyzer
        run: dart analyze