name: Dart Analyze

on: [push]

jobs:
  analyze:
    name: Analyze Dart Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Change to project directory
        working-directory: GAIA_Project/code/app/GAIA/
        run: |
          dart pub get
          dart analyze