name: Flutter Analyze

on: [push]

jobs:
  analyze:
    name: Analyze Flutter Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: code/app/GAIA
        run: flutter pub get

      - name: Recreate Ip_config file
        working-directory: code/app/GAIA
        run: |
            mkdir -p lib/config
            echo "${{ secrets.IP_CONFIG_CONTENT}}" > lib/config/ip_config.dart

      - name: Analyze code
        working-directory: code/app/GAIA
        run: flutter analyze